### ISSUE TITLE
Posible Incompatibilty

### ISSUE THREAD

**Issue by PabloArty** [jameskoster/woocommerce-product-image-flipper#11]
Hi! I'm working with Divi 3.0.5, Wordpress 4.7.5, Woocommerce 3.0.7, and the flipper is not working ): When hover i just see a white layer with 80% opacity appear, here is my site:

http://www.mariamichaud.com/es/

**Comment by jameskoster** [comment]
Hey, I suggest contacting Divi support about this if you need an integration with that theme. They should be able to help you :)

I'm going to close this because it's not a 'bug' with this plugin.
