### ISSUE TITLE
Not working with woocommerce shortcodes

### ISSUE THREAD

**Issue by xbass540** [jameskoster/woocommerce-product-image-flipper#14]
I actually reproduce one of wordpress.org support tickets that i also face:

The plugin works perfectly on woocommerce pages, for example a woocommerce category page displaying all products. It does not work when I use a woocommerce shortcode to embed a product category on a page.

thanks for the great work!

**Comment by jameskoster** [comment]
Can you share a URL for me to investigate. I can't see any obvious reason why it wouldn't work.

**Comment by xbass540** [comment]
hi,
thanks for the fast reply, just emailed you with some login details!

**Comment by jameskoster** [comment]
I didn't receive an email?

**Comment by xbass540** [comment]
i replied at the e-mail (James Koster <notifications@github.com>) received by github. I send it again. Thanks

**Comment by xbass540** [comment]
hi, did you have some time to check the issue? it is really important to our new website :)

**Comment by jameskoster** [comment]
That's not my email address. Can you share the URL here please?

**Comment by xbass540** [comment]
hi this is a commercial web site currently offline, i need to give you login credentials. Could you please send me an email to xbass540@yahoo.gr and i will send you the login credentials?

**Comment by jameskoster** [comment]
it's ok, I just replicated this locally. I'll work on a fix asap.
