### ISSUE TITLE
can't use with load more products 

### ISSUE THREAD

**Issue by mikekosulin** [jameskoster/woocommerce-product-image-flipper#9]
Works only with "the first page"
Not works after loading more products

Using:
https://ru.wordpress.org/plugins/load-more-products-for-woocommerce/

**Comment by jameskoster** [comment]
It's because I'm using js for the animations. Need to update that to use pure CSS.

**Comment by AlexanderBMAS** [comment]
I identified a similar issue using a custom ajax load more, the add_filter for the has-gallery class does not fire on the post_class call as the add class action is wrapped in ! is_admin filter which conflicts with admin-ajax.
